const images = {
  john: require('../images/john.jpg'),
  logo: require('../images/logo.png'),
  getstartedback: require('../images/getstartedback.png'),
  curve: require('../images/letsee.png'),
  tutorialsblue: require('../images/tutorialsblue.png'),
  tutorialsblack: require('../images/tutorialsblack.png'),
  back: require('../images/back.png'),
  program: require('../images/program.png'),
  store: require('../images/store.png'),
  storeblue: require('../images/storeblue.png'),
  letsee: require('../images/letsee.png'),
  menu: require('../images/menu.png'),
  completed: require('../images/completed.png'),
  programback: require('../images/programback.png'),
  gradientBlack: require('../images/gradientBack.png'),
  gradient: require('../images/gradient.png'),
  dummy: require('../images/dummy.png'),
  heart: require('../images/heart.png'),
  pdf: require('../images/pdf.png'),
  cross: require('../images/cross.png'),
  share: require('../images/share.png'),
  logout: require('../images/logout.png'),
  deleteAccount: require('../images/deleteAccount.png'),
  leaf: require('../images/leaf.png'),
  account: require('../images/account.png'),
  exerciseFirst: require('../images/exerciseFirst.png'),
  exerciseBack: require('../images/exerciseBack.png'),

  home: require('../images/home.png'),
  bag: require('../images/bag.png'),
  user: require('../images/user.png'),
  like: require('../images/like.png'),
};

export default images;
