import {StyleSheet} from 'react-native';
import {dW, dH, windowHeight, windowWidth} from '../Utils/dynamicHeightWidth';
import assets from '../assets/images/index';
import colors from '../constants/colors';
const useStyle = () => {
  return StyleSheet.create({
    curve_long: {
      height: dH(20),
      marginTop: 0,
      width: dW(30),
      //resizeMode: 'cover',
    },
    sender_img: {height: 30, width: 30, borderRadius: 15, marginTop: 8},
    left_msg_c: {
      flexDirection: 'row',
      marginTop: 20,
      paddingRight: 90,
      //backgroundColor: 'white',
      // padding: 10,
    },
    left_msg_c_c: {
      flexDirection: 'row',
      // marginTop: 20,
      backgroundColor: 'white',
      padding: 15,
      marginLeft: 10,
      borderRadius: 10,
    },
    left_msg_time: {
      color: colors.primary,
      marginLeft: 10,
      marginTop: 3,
      fontSize: 12,
    },
    left_msg: {
      marginLeft: 10,
      marginTop: 3,
      fontSize: 12,
      color: colors.white,
    },

    right_msg_c: {
      flexDirection: 'row',
      alignSelf: 'flex-end',
      marginTop: 20,
      paddingLeft: 90,
      // backgroundColor: '#863BC0',
    },
    right_msg_c_c: {
      alignSelf: 'flex-end',
      alignItems: 'flex-end',
      borderRadius: 10,
      backgroundColor: '#863BC0',

      padding: 15,
      marginRight: 10,
    },
    right_msg_text: {
      color: colors.white,
      marginRight: 10,
      marginTop: 0,
      fontSize: 12,
    },
    right_msg: {
      marginRight: 10,
      marginTop: 0,
      fontSize: 12,
      borderRadius: 10,
    },
    header_img: {height: dH(380), widht: '100%'},
    curve_img: {height: dH(15), marginTop: 15},
    BottomSheet_container: {
      alignItems: 'center',
      borderRadius: 19,
    },
    dummy: {
      height: 180,
      width: windowWidth() - dW(20),
    },
    tutorial: {
      flexDirection: 'column',
      width: windowWidth() - 0,
      paddingHorizontal: 30,
      marginTop: dW(10),
      // backgroundColor: 'red',
    },
    btn_heading: {
      textAlign: 'center',
      fontSize: dW(15),
      marginTop: dW(0),
      lineHeight: 25,
      letterSpacing: 1,
      color: colors.white,
      fontFamily: 'Montserrat-SemiBold',
    },
    primaryBtn: {
      backgroundColor: colors.button,
      alignSelf: 'center',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 20,
      paddingHorizontal: 20,
      height: 48,
      width: '85%',
      borderRadius: 20,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,

      elevation: 5,
    },
    test: {
      textAlign: 'left',
      fontSize: dW(17),
      marginTop: dW(0),
      lineHeight: 27,
      letterSpacing: 1,
      color: colors.gray,
      fontFamily: 'Montserrat-SemiBold',
    },
    corner: {
      flexDirection: 'column',
      width: windowWidth() - 0,
      paddingHorizontal: 30,
    },
    lets: {
      textAlign: 'left',
      fontSize: dW(23),
      marginTop: dW(0),
      lineHeight: 27,
      letterSpacing: 1,
      color: colors.primary,
      fontFamily: 'Montserrat-Bold',
    },
    corner_img: {height: 300, widht: '100%', marginTop: dW(70)},
    heading_a4: {
      color: colors.white,
      fontFamily: 'Montserrat-Bold',
      fontSize: dW(18),
    },
    items_lane_inner: {
      width: '98%',
      height: '100%',

      alignSelf: 'flex-end',
      //marginTop: 110,
      paddingHorizontal: 10,
      borderRadius: 6,
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    items_lane_inner1: {
      width: '100%',
      height: '100%',
      alignSelf: 'flex-end',
      //marginTop: 110,
      paddingHorizontal: 10,
      borderRadius: 6,
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    image_main0: {
      height: 180,
      width: windowWidth() - dW(18),
      // margin: 5,
    },
    image_main: {
      height: 180,
      width: windowWidth() - dW(70),
      // margin: 5,
    },
    image_main1: {
      height: 180,
      width: windowWidth() - 30,
      // margin: 5,
    },
    parent_contaier_bottomsheet: {
      width: '100%',
      paddingHorizontal: 30,
      paddingVertical: 25,
      justifyContent: 'center',
      alignItems: 'center',
    },
    item_lane: {
      // height: 180,
      // alignItems: 'center',
      // justifyContent: 'center',
      borderRadius: 5,
      height: 180,
      width: windowWidth() - dW(68),
      // margin: 7,
    },
    heading__: {
      color: colors.black,
      fontFamily: 'Montserrat-Bold',
      fontSize: dW(18),
    },
    heading__viewall: {
      color: colors.black,
      fontFamily: 'Montserrat-Light',
      fontSize: dW(13),
      marginRight: 10,
    },
    items_inn: {
      height: 230,
      padding: 10,
      marginTop: 0,
    },
    bottomSheet_btn: {
      backgroundColor: colors.primary,
      width: '100%',
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
    },
    btn_heading_black: {
      color: colors.white,
      fontSize: 14,
      letterSpacing: 1,
      fontFamily: 'Montserrat-Medium',
    },
    bottomSheet_btn_margin: {
      backgroundColor: colors.primary,
      width: '100%',
      height: 50,
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 8,
      marginTop: 10,
    },
    recovery: {
      //textAlign: 'center',
      fontSize: dW(14),
      marginTop: dW(0),
      lineHeight: 15,
      letterSpacing: 1,
      color: colors.primary,
      fontFamily: 'Montserrat-Bold',
    },
    mt_2: {
      marginTop: 2,
    },
    ground3: {
      //textAlign: 'center',
      fontSize: dW(15),
      marginTop: 7,
      color: colors.white,
      fontFamily: 'Montserrat-Regular',
    },
    primaryHeader: {
      height: 55,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    ground2: {
      //textAlign: 'center',
      fontSize: dW(18),
      marginTop: 7,
      color: colors.white,
      fontFamily: 'Montserrat-Bold',
    },
    editprofilelane_inner: {
      flex: 0.9,
      flexDirection: 'row',
      paddingLeft: 10,
      alignItems: 'center',
    },
    hea_ing: {paddingLeft: 5, color: colors, fontSize: 15},
    editprofilelane: {
      height: 50,
      backgroundColor: colors.lightgray,
      flexDirection: 'row',
      marginTop: 12,
      borderRadius: 5,
    },
    //  curve_long: {height: dH(15), marginTop: 0, width: dW(70)},
    menuimg: {height: dH(20), marginTop: 0, width: dW(20)},
    all_center: {justifyContent: 'center', alignItems: 'center'},
    messageus: {
      marginTop: 30,
      fontSize: 17,
      fontFamily: 'Montserrat-Medium',
      textDecorationLine: 'underline',
    },
    edit: {
      marginTop: 20,
      textDecorationLine: 'underline',
      fontSize: 17,
      fontFamily: 'Montserrat-Medium',
    },
    inner: {
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 30,
    },
    back_tut: {
      height: 400,
      marginTop: dW(-20),
      //  backgroundColor: 'red',
    },
    browse: {
      textAlign: 'left',
      fontSize: dW(17),
      marginTop: dW(0),
      lineHeight: 27,
      letterSpacing: 1,
      color: colors.secondary,
      fontFamily: 'Montserrat-SemiBold',
    },
    explore: {
      textAlign: 'left',
      fontSize: dW(17),
      marginTop: dW(0),
      lineHeight: 27,
      letterSpacing: 1,
      color: colors.secondary,
      fontFamily: 'Montserrat-SemiBold',
    },
    tut1: {
      textAlign: 'left',
      fontSize: dW(23),
      marginTop: dW(-10),
      lineHeight: 27,
      letterSpacing: 1,
      color: colors.primary,
      fontFamily: 'Montserrat-Bold',
    },
    tut: {
      textAlign: 'left',
      fontSize: dW(23),
      marginTop: dW(-63),
      lineHeight: 27,
      letterSpacing: 1,
      color: colors.primary,
      fontFamily: 'Montserrat-Bold',
    },
    turorial: {
      flexDirection: 'column',
      width: windowWidth() - 0,
      paddingHorizontal: 30,
    },
    store_n: {
      marginTop: dW(47),
      textAlign: 'left',
      fontSize: dW(23),

      lineHeight: 27,
      letterSpacing: 1,
      color: colors.primary,
      fontFamily: 'Montserrat-Bold',
    },
    walk_img: {
      height: 235,
      widht: '100%',
      justifyContent: 'center',
      alignContent: 'center',
      marginTop: dW(45),
    },
    walk_lane: {
      flexDirection: 'column',
      width: windowWidth() - 0,
      //   paddingHorizontal: 30,
    },
    store: {
      height: 90,
      width: '90%',
      alignSelf: 'center',
      marginLeft: 10,
      //margin: 5,
    },
    rocom_lane_list_item: {
      height: 110,
      width: 120,
      backgroundColor: colors.white,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      margin: 5,
      elevation: 5,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    recom: {
      height: 200,
      paddingHorizontal: 20,
      marginTop: 20,
    },
    recom_lane: {
      height: 170,
      alignItems: 'center',
      justifyContent: 'center',
    },
    train: {
      textAlign: 'left',
      fontSize: dW(17),
      marginTop: dW(0),
      lineHeight: 27,
      letterSpacing: 1,
      color: colors.secondary,
      fontFamily: 'Montserrat-SemiBold',
    },
    backtramsform: {
      height: 15,
      width: 15,
      resizeMode: 'contain',
      transform: [{rotate: '180deg'}],
    },
    program: {
      textAlign: 'left',
      fontSize: dW(23),
      marginTop: dW(-30),
      lineHeight: 27,
      letterSpacing: 1,
      color: colors.primary,
      fontFamily: 'Montserrat-Bold',
    },
    walk: {
      flexDirection: 'column',
      width: windowWidth() - 0,
      paddingHorizontal: 30,
      marginTop: dW(-30),
    },
    walkImg: {
      height: 400,
      widht: '100%',
      marginTop: dW(-10),
    },
    contain_back: {
      backgroundColor: colors.white,
      height: 35,
      width: 35,
      borderRadius: 17,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 7,
      },
      shadowOpacity: 0.41,
      shadowRadius: 9.11,

      elevation: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mold_view: {
      width: '100%',
      height: 180,
      alignSelf: 'flex-end',
      paddingHorizontal: 10,
      alignItems: 'flex-start',
      justifyContent: 'center',
      flexDirection: 'row',
    },
    lane_of: {
      flex: 0.2,

      height: '100%',
      alignItems: 'center',
      justifyContent: 'center',
    },
    jallus: {
      marginTop: 120,
      color: colors.white,
      fontFamily: 'Montserrat-Bold',
      fontSize: dW(18),
    },

    produchList: {
      padding: 0,
      marginTop: 0,
    },
    dummy_img: {
      height: 180,
      width: windowWidth() - dW(20),
    },
    lane_product: {
      height: 180,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 10,
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      margin: 4,
      elevation: 5,
    },
    ballk: {height: dH(17), marginTop: 0, width: dW(17)},
    curve__: {height: dH(20), marginTop: 30, width: dW(30)},
    drawer: {
      flex: 1,
      backgroundColor: 'white',
      width: '100%',
      alignItems: 'center',
    },
    headingProduct: {
      color: colors.black,
      fontFamily: 'Montserrat-Bold',
      fontSize: dW(15),
      paddingLeft: 10,
    },
    emptyView: {
      backgroundColor: 'transparent',
      height: windowHeight() / 1.4,
      width: windowWidth(),
      justifyContent: 'center',
      alignItems: 'center',
    },
    empview: {height: dH(20), marginTop: 0, width: dW(20)},
    curve: {height: dH(15), marginTop: 0, width: dW(70)},
    back_img_ext: {height: dH(22), marginTop: 0, width: dW(22)},
    back_img: {height: dH(15), marginTop: 0, width: dW(15)},
    back: {
      height: 55,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 20,
    },
    ground1: {
      //textAlign: 'center',
      fontSize: dW(12),
      marginTop: 6,
      color: colors.secondary,
      fontFamily: 'Montserrat-SemiBold',
    },
    ground: {
      //textAlign: 'center',
      fontSize: dW(12),

      color: colors.gray,
      fontFamily: 'Montserrat-Regular',
    },
    access: {
      textAlign: 'center',
      fontSize: dW(15),
      marginTop: dW(20),
      lineHeight: 19,
      letterSpacing: 0,
      color: colors.gray,
      fontFamily: 'Montserrat-Medium',
    },
    and: {
      textAlign: 'center',
      fontSize: dW(15),
      marginTop: dW(2),
      lineHeight: 19,
      letterSpacing: 0,
      padding: 0,
      color: 'gray',
      fontFamily: 'Montserrat-Medium',
    },
    have: {
      textAlign: 'center',
      fontSize: dW(15),
      marginTop: dW(15),
      lineHeight: 19,
      letterSpacing: 0,
      padding: 0,
      color: 'gray',
      fontFamily: 'Montserrat-Medium',
    },
    drawn_: {
      height: 55,
      backgroundColor: colors.lightgray,
      flexDirection: 'row',
      marginTop: 12,
      borderRadius: 5,
    },
    backl: {
      height: 15,
      width: 15,
      resizeMode: 'contain',
      transform: [{rotate: '180deg'}],
    },
    drawer_11: {
      flex: 0.1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingRight: 10,
    },
    imgg_: {
      height: 30,
      width: 30,
      resizeMode: 'cover',
    },
    drawn_inner: {
      flex: 0.9,
      flexDirection: 'row',
      paddingLeft: 20,
      alignItems: 'center',
    },
    login: {
      textAlign: 'center',
      fontSize: dW(16),
      marginTop: dW(10),
      lineHeight: 19,
      letterSpacing: 0,
      padding: 0,
      color: 'gray',
      fontFamily: 'Montserrat-SemiBold',
    },
  });
};
export default useStyle;
