import {StyleSheet} from 'react-native';
import {
  dW,
  dH,
  windowHeight,
  windowWidth,
} from '../../Utils/dynamicHeightWidth';
import assets from '../../assets/images/index';
import colors from '../../constants/colors';
const useStyle = () => {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    titleText: {
      flex: 1,
      fontSize: 22,
      fontWeight: 'bold',
    },
    header: {
      backgroundColor: 'white',
      marginTop: 10,
      paddingHorizontal: 20,
      paddingVertical: 10,
      flexDirection: 'row',
      height: 90,
      borderBottomWidth: 1,
      borderBottomColor: colors.lightgray,
    },
    header11: {
      backgroundColor: 'white',
      // marginTop: 10,
      paddingHorizontal: 20,
      paddingVertical: 10,
      flexDirection: 'row',
      height: 60,
      borderBottomWidth: 1,
      borderBottomColor: colors.lightgray,
    },
    headerText1: {
      fontSize: 16,
      fontFamily: 'Montserrat-Medium',
      marginLeft: 10,
      width: '75%',
    },
    headerText: {
      fontSize: 14,
      fontFamily: 'Montserrat-Regular',
      marginLeft: 10,
      width: '65%',
    },
    separator: {
      height: 0.5,
      backgroundColor: '#808080',
      width: '95%',
      marginLeft: 16,
      marginRight: 16,
    },
    text: {
      fontSize: 13,
      color: '#606070',
      padding: 10,
      marginLeft: 120,
      // width: 120,
      //textAlign: 'right',
    },
    content: {
      // paddingLeft: 10,
      // paddingRight: 10,
      backgroundColor: '#fff',
    },
    image: {
      height: 70,
      width: 70,
      borderRadius: 10,
      resizeMode: 'cover',
    },
    tou: {flexDirection: 'row', alignItems: 'center'},

    dataaa: {
      height: dH(12),
      //  marginRight: 10,
      width: dW(12),
      transform: [{rotate: '270deg'}],
    },
    dataaa1: {
      height: dH(25),
      marginRight: 15,
      width: dW(25),
      //transform: [{rotate: '270deg'}],
    },
    flex3: {flex: 0.3},
    flex7: {flex: 0.7},
    imageee: {
      // borderRadius: 10,
      marginTop: 10,
      marginRight: 20,
      // backgroundColor: 'red',
      height: 160,
      flex: 1,
      alignSelf: 'flex-end',
      width: dW(240),
    },
    header_img: {height: dH(380), widht: '100%'},
    curve_img: {height: dH(15), marginTop: 15},
    recovery: {
      //textAlign: 'center',
      fontSize: dW(17),
      marginTop: dW(0),
      lineHeight: 20,
      letterSpacing: 1,
      color: colors.primary,
      fontFamily: 'Montserrat-Bold',
    },
    mt_2: {
      marginTop: 2,
    },
    header1: {flex: 0.9, flexDirection: 'row', alignItems: 'center'},
    ground3: {
      //textAlign: 'center',
      fontSize: dW(15),
      marginTop: 7,
      color: colors.white,
      fontFamily: 'Montserrat-Regular',
    },
    ground2: {
      //textAlign: 'center',
      fontSize: dW(16),
      marginLeft: 7,
      color: colors.black,
      fontFamily: 'Montserrat-Medium',
    },
    renderWeek: {
      margin: 6,
      height: 35,
      width: 100,
      borderRadius: 5,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ground1: {
      //textAlign: 'center',
      fontSize: dW(12),
      marginTop: 10,
      color: colors.gray,
      fontFamily: 'Montserrat-Regular',
    },
    cover: {
      marginTop: 10,
      marginRight: 20,
      // backgroundColor: 'red',
      height: 160,
      flex: 1,
      alignSelf: 'flex-end',
      width: dW(240),
    },
    flex: {flex: 0.7},

    backim: {
      height: dH(12),
      marginRight: 10,
      width: dW(12),
      transform: [{rotate: '270deg'}],
    },
    data: {
      flex: 0.1,
      flexDirection: 'row',
      alignItems: 'center',
    },
    dummy: {
      height: 70,
      width: 70,
      borderRadius: 10,
      resizeMode: 'cover',
    },

    rehab: {
      color: colors.gray,
      fontFamily: 'Montserrat-Medium',
      fontSize: dW(16),
      paddingHorizontal: 20,
    },
    mask: {
      backgroundColor: colors.lightgray,
      height: 1,
      width: '90%',
      alignSelf: 'center',
      marginTop: 10,
    },
    emp: {
      backgroundColor: colors.lightgray,
      height: 1,
      width: '90%',
      alignSelf: 'center',
      marginTop: 10,
    },
    save: {
      fontSize: 12,
      fontFamily: 'Montserrat-Regular',
      color: 'gray',
    },
    pdfV: {
      justifyContent: 'center',
      alignItems: 'center',
      flex: 0.2,
    },
    pdf: {height: 22, width: 22},
    dot: {
      marginTop: 10,
      //justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
      flex: 0.8,
    },
    details: {
      flex: 1,
      height: 55,
      // backgroundColor: 'gray',
      paddingHorizontal: 20,
      justifyContent: 'center',
      // alignItems: 'space-between',
      flexDirection: 'row',
    },
    dum: {
      height: 190,
      width: '100%',
    },
    paddingV: {paddingVertical: 5},
    ground0: {
      //textAlign: 'center',
      fontSize: dW(13),
      marginTop: 0,

      fontFamily: 'Montserrat-Medium',
    },
    ground: {
      //textAlign: 'center',
      fontSize: dW(12),

      color: colors.gray,
      fontFamily: 'Montserrat-Regular',
    },
    access: {
      textAlign: 'center',
      fontSize: dW(15),
      marginTop: dW(20),
      lineHeight: 19,
      letterSpacing: 0,
      color: colors.gray,
      fontFamily: 'Montserrat-Medium',
    },
    and: {
      textAlign: 'center',
      fontSize: dW(15),
      marginTop: dW(2),
      lineHeight: 19,
      letterSpacing: 0,
      padding: 0,
      color: 'gray',
      fontFamily: 'Montserrat-Medium',
    },
    have: {
      textAlign: 'center',
      fontSize: dW(15),
      marginTop: dW(15),
      lineHeight: 19,
      letterSpacing: 0,
      padding: 0,
      color: 'gray',
      fontFamily: 'Montserrat-Medium',
    },
    login: {
      textAlign: 'center',
      fontSize: dW(16),
      marginTop: dW(10),
      lineHeight: 19,
      letterSpacing: 0,
      padding: 0,
      color: 'gray',
      fontFamily: 'Montserrat-SemiBold',
    },
  });
};
export default useStyle;
